### ISSUE TITLE
Implement textpad tab (Tp)

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#154]
AC
- [x] Implement the Cj tab
- [x] Retain parity with DPR palemoon
- [x] [Fixed through #173] Ensure context menu button "send to text pad" works
- [x] [Fixed through #173] Ensure keyboard shortcut "Send selected text to textpad" works
- [x] [Fixed through #173] Ensure keyboard shortcut "Append selected text to textpad" works

Notes:
- This is the one:
   ![image](https://user-images.githubusercontent.com/2140460/76698787-a5eb4700-66f2-11ea-99e0-5de006d94b45.png)

**Comment by parthopdas** [comment]
in production
